version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "559050205029"
    AWS_REGION: "us-east-1"
    ECR_REPO_NAME: "chess-pl-sql-ecr-repo"  # Replace with your ECR repository name
    IMAGE_TAG: "latest"  # Tag for the latest image
    IMAGE_NAME: "your-image-name"  # Name of the Docker image
    CLUSTER_NAME: "chess-pl-sql"
    SERVICE_NAME: "chess-pl-sql-svc"	

phases:
  install:
    runtime-versions:
      python: 3.12 
    commands:
      - echo "Logging in to ECR"
      # Authenticate to ECR using aws ecr get-login-password
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Login successful"

  pre_build:
    commands:
      - echo "Building Docker image"
      # Generate the version tag based on the current date and time (dd-mm-yyyy-hh-mm-ss)
      - VERSION_TAG=$(date +%d-%m-%Y-%H-%M-%S)
      - echo "Version tag is $VERSION_TAG"
      # Build the Docker image and tag it with the version tag
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$VERSION_TAG .
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$VERSION_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo "Docker image built and tagged with $VERSION_TAG and $IMAGE_TAG"

  build:
    commands:
      - echo "Pushing Docker image to ECR"
      # Push the versioned tag and the latest tag to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$VERSION_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Creating ECS imagedefinitions.json"
      # Create the imagedefinitions.json file for ECS with the dynamic version tag
      - printf '[{"name":"chess-pl-sql","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $AWS_ACCOUNT_ID $AWS_REGION $ECR_REPO_NAME $VERSION_TAG > imagedefinitions.json
      - echo "imagedefinitions.json created with version tag $VERSION_TAG"

artifacts:
  files:
    - imagedefinitions.json
